import express from 'express';
import fetch from 'node-fetch';
const router = express.Router();
import dotenv from 'dotenv';
dotenv.config();
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
router.post('/story', async (req, res) => {
  const { emotion, text } = req.body;

  if (!emotion || !text) {
    return res.status(400).json({ error: 'Missing emotion or text.' });
  }

  if (!OPENAI_API_KEY) {
    return res.status(500).json({ error: 'Missing OpenAI API key' });
  }

  const prompt = `
You are an AI storyteller for young girls learning to code.
Based on the emotion "${emotion}" and the student's sentence: "${text}",
write a short, 3-5 sentence story that reflects the emotion and encourages her
journey in technology. Use simple language, positive framing, and make the story
easy to visualize.
`;

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.8
      })
    });

    const data = await response.json();
    console.log("🧾 OpenAI full response:", JSON.stringify(data, null, 2));
        if (!response.ok) {
      console.error('OpenAI API error:', data);
      return res.status(500).json({ error: data?.error?.message || 'Failed to generate story from OpenAI' });
    }

    const story = data.choices?.[0]?.message?.content?.trim();

    if (!story) {
      return res.status(500).json({ error: 'No story generated by model.' });
    }

    return res.json({ story });
  } catch (err) {
    console.error('Story generation failed:', err);
    return res.status(500).json({ error: 'Failed to generate story.' });
  }
});

export default router;